# This is a generated file. Not intended for manual editing.
services:
  transaction.api:
    build:
      context: "/Users/maks/RiderProjects/TransMang/TransactionManagement"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/TransactionManagement.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "mathhunt.api:dev"
    ports: []
    volumes:
    - "/Users/maks/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/maks/RiderProjects/TransMang/TransactionManagement:/app:rw"
    - "/Users/maks/RiderProjects/TransMang:/src:rw"
    working_dir: "/app"
